API_VERSION = 'v1'
API_PATH = '/api/{}'.format(API_VERSION)
APP_SECRET_KEY = "jagger"
DEBUG = True
FIREBASE_KEY_PATH = './firebase/jagger-games-661aab4375ad.json'

# FIREBASE DB CONSTANTS
QUESTIONS_FB_DB = 'questions'
ANSWERS_FB_DB = 'answers'
TAGS_FB_DB = 'tags'


# GAME CONSTANTS

# TIME LIMIT CALCULATIONS
MIN_TIME_LIMIT = 5
DIFF_WEIGHT = 0.25
TYPE_WEIGHT = 0.25
LEN_WEIGHT = 0.5






