API_VERSION = 'v1'
API_PATH = '/api/{}'.format(API_VERSION)
APP_SECRET_KEY = "jagger"
DEBUG = True


# GAME CONSTANTS

# TIME LIMIT CALCULATIONS
MIN_TIME_LIMIT = 5
DIFF_WEIGHT = 0.25
TYPE_WEIGHT = 0.25
LEN_WEIGHT = 0.5

